Massive improvement in syntax and features

diff --git a/home/bin/clean b/home/bin/clean
--- a/home/bin/clean
+++ b/home/bin/clean
@@ -1,19 +1,55 @@
-#!/bin/bash
+#!/usr/bin/bash
 
-if [[ $# -gt 1 ]]; then
-  echo "ERROR: Too many arguments" 1>&2
-  exit 1
-fi
-if [[ "$1" =~ ^-{1,2}h(elp)?$ ]]; then
-  echo "SYNTAX: clean [all]"
-  exit 0
+SYNTAX="SYNTAX: clean [-exe|-logs|-all] [DIRLIST]"
+
+function Realpath () {
+  test -z "$*" && echo "" || \
+  perl '-MCwd(abs_path)' -le "print abs_path(qq($*))"
+}
+
+unset DIRS
+declare -a DIRS
+V='-v'
+let i=0
+OPTS=
+while [[ $# -gt 0 ]]; do
+  if [[ "$1" =~ ^-{1,2}h(elp)?$ ]]; then
+    echo $SYNTAX
+    exit 0
+  elif [[ "$1" =~ ^-{1,2}q(uiet)?$ ]]; then
+    V=''
+  elif [[ "$1" =~ ^-{1,2}v(erbose)?$ ]]; then
+    V='-v'
+  elif [[ "$1" =~ ^-all$ ]]; then
+    OPTS=A
+  elif [[ "$1" =~ ^-exe$ ]]; then
+    OPTS+=X
+  elif [[ "$1" =~ ^-logs$ ]]; then
+    OPTS+=L
+  elif [[ "$1" =~ ^- ]]; then
+    echo "ERROR: Bad option '$1'." 1>&2
+    exit 1
+  elif [[ -d "$1" ]]; then
+    let ++i
+    DIRS[$i]="$1"
+  else
+    echo "ERROR: Bad directory '$1'." 1>&2
+    exit 1
+  fi
+  shift
+done
+if [[ ${#DIR[@]} == 0 ]]; then
+  DIR[1]=.
 fi
 
-find . -name '*.[doxP]' -exec rm -v {} \;
-if [[ "$1" == all ]]; then
-  find . -name '*.log' -exec rm -v {} \;
-  test -d build && rm -fr build/* build/.???*
-elif [[ "$1" == spotless ]]; then
-  find . -name '*.log' -exec rm -v {} \;
-  test -d build && rm -fr build
-fi
+for DIR in ${DIRS[@]}; do
+  find "$DIR" -name '*.[doP]' -exec rm $V {} \;
+  if   [[ $COMMAND =~ L ]]; then
+    find "$DIR" -type f -name '*.log' -exec rm $V {} \;
+  elif [[ $OPTS =~ X ]]; then
+    find "$DIR" -type f -name '*.x' -exec rm $V {} \;
+  elif [[ $OPTS =~ A ]]; then
+    find "$DIR" -type f -name '*.log' -exec rm $V {} \;
+    find "$DIR" -type d -name build -exec rm $V -fr build \;
+  fi
+done
